#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap -layout gb
xrdb ~/.Xresources
~/.config/scripts/pscircle.sh
~/.config/scripts/xautolock.sh &
~/.config/scripts/lemonbar.sh & 
